position = "bottom"
height = 30
center = []

[[start]]
type = "workspaces"

[[end]]
type = 'sys_info'
format = [
    " {memory_used}/{memory_total}GB",
    "󰋊 {disk_used#G@/:.1}/{disk_total#G@/:.1}GB",
    "→{disk_read:.1}MB/s",
    "←{disk_write:.1}MB/s",
    "↑{net_down:.1}Mbps",
    "↓{net_up}Mbps",
    " {load_average_1}",
]

[end.interval]
cpu = 1
disks = 300
memory = 30
networks = 3
temps = 5


[[end]]
type = "volume"


[[end]]
type = "clock"
format = " %Y-%m-%d %H:%M"

[[end]]
type = "tray"
icon_size = 16
